let restaurantData = [{"name": ["Pork & Lemongrass", 
                                "Shitake & Ingwer", 
                                "Shrimp & Koriander", 
                                "Chicken & Sesame", 
                                "Beef & Thai-Chilli", 
                                "Tofu & Mango"],
                        "description": ["Dumplings mit Schweinefleisch und Lemongrass nach Art des Hauses", 
                                        "Dumplings mit Shitake und Ingwer (vegetarisch)", 
                                        "Dumplings mit Shrimp und Koriander", 
                                        "Dumplings mit Huhn und gerösteten Sesamsamen", 
                                        "Dumplings mit Rind und scharfem Thai-Chilli", 
                                        "Dumplings mit Tofu und Mango (vegetarisch)"],
                        "price": [4.9, 3.9, 5.9, 4.9, 3.9, 4.9],
                        "title": "Ho Mai Chinese Dumplings",
                        "ratings": 3945},

                        {"name": ["Strawberry Glaze", 
                                "Rainbow Glance", 
                                "Yellow Surprise", 
                                "Pink Smash", 
                                "Green Volcano", 
                                "Glazier Fire"], 
                        "description": ["Doughnut mit Erdbeerglasur und Crèmefüllung", 
                                        "Doughnut mit Regenbogenglasur, Streuseln und Fruchtfüllung", 
                                        "Doughnut mit Zitronenglasur und Mandelstreuseln", 
                                        "Doughnut mit Himbeerglasur und Crèmefüllung", 
                                        "Veganer Doughnut mit Fruchtfüllung und grüner Glasur", 
                                        "Doughnut mit Schokoladenfüllung und Schokoladenglaseur"], 
                        "price": [2.95, 2.95, 3.5, 3.5, 3.95, 2.95], 
                        "title": "Las Vegas Doughnuts", 
                        "ratings": 129},

                        {"name": ["Margherita", 
                                "Quattro Formaggi", 
                                "Parma",
                                "Ortolana", 
                                "Spinaci", 
                                "Mozzarella di Bufalo"], 
                        "description": ["Pizza mit Mozzarella und Tomatensauce", 
                                        "Pizza mit Mozzarella, Scarmorza, Gorgonzola und Mascarpone", 
                                        "Pizza mit Mozzarella, Rucola, Walnüssen und Parmaschinken", 
                                        "Pizza mit gegrillten Auberginen, Lauchzwiebeln, Roma-Tomaten und Mascarpone", 
                                        "Pizza mit frischem Babyspinat, Mozzarella und Knoblauch", 
                                        "Pizza mit Büffelmozzarella"], 
                        "price": [11.95, 13.95, 15.5, 13.5, 13.95, 15.5], 
                        "title": "Pizza di Rocco", 
                        "ratings": 1298}, 

                        {"name": ["Romana & Vegan Cheese", 
                                    "Rucola & Green Beans", 
                                    "Kopfsalat & Linsen", 
                                    "Babyspinat & Nuts",
                                    "Mais & Feldsalat",
                                    "Sellerie & Frisée"],
                        "description": ["Romanasalat mit Variation von veganem Ziegenkäse", 
                                        "Rucolasalat mit einer Auswahl verschiedener Bohnen", 
                                        "Kopfsalat mit roten und gelben Linsen", 
                                        "Babyspinat mit Sonnenblumen und Pinienkernen", 
                                        "Feldsalat mit frisch gerösteten, jungen Maiskolben",
                                        "Friséesalat mit Selleriecarpaccio"],
                        "price": [9.5, 8, 8.5, 7.5, 10, 9.95], 
                        "title": "Vegan Salad Bowls", 
                        "ratings": 81}, 

                        {"name": ["Chocolate Marseille", 
                        "Limon Paris", 
                        "Strawberry Bordeaux", 
                        "Rasberry Lyon", 
                        "Almond Strasbourg", 
                        "Blueberry Rennes"], 
                        "description": ["Zartschmelzender Schokoladentarte", 
                                        "Zitronentarte mit einem Hauch von Ingwer", 
                                        "Erdbeertarte mit Baiserkronen", 
                                        "Himbeertarte mit Dinkelmürbeteig und karamellisierten Haselnüssen", 
                                        "Mandeltarte mit Marzipanfüllung und einer leichten Orangennote", 
                                        "Blaubeertarte mit Crème-Füllung und weißer Schokolade"], 
                        "price":[14, 9.95, 12, 13.5, 13.95, 12.5], 
                        "title": "Marie's Tartelettes", 
                        "ratings": 219},

                        {"name": ["Palak Paneer", 
                                "Mattar Paneer", 
                                "Shahi Paneer", 
                                "Paneer Masala", 
                                "Paneer Mahkni", 
                                "Paneer Jalfrezi"], 
                        "description": ["Hausgemachter Rahmkäse mit Spinat und Gewürzen", 
                                        "Hausgemachter Rahmkäse mit grünen Erbsen",
                                        "Hausgemachter Rahmkäse nach Art des Hauses mit Cashewnüssen und Mandeln",
                                        "Hausgemachter Rahmkäse mit Zwiebeln, Tomaten und Gewürzen",
                                        "Hausgemachter Rahmkäse in Butter-Tomatensauce", 
                                        "Hausgemachter Rahmkäse mit Paprika, Zwiebeln, Ingwer und Knoblauch"], 
                        "price": [8.95, 6.95, 9, 12.95, 11, 9.95], 
                        "title": "Asahi Shimbun Paneer",
                        "ratings": 192}];
                    
